# Generated by Django 3.2 on 2022-05-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_todos_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Very Important', 'Very Important'), ('Important', 'Important'), ('Normal', 'Normal')], default='very_important', max_length=50),
        ),
    ]
